name: CI

on: [push, pull_request]

env:
  RUBY: 2.7

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ env.RUBY }}"
          bundler-cache: true

      - name: Version info
        run: |
          ruby --version
          gem --version
          bundle --version

      - run: bundle exec jekyll build
      - run: bundle exec jekyll doctor

      - name: Run html-proofer
        run: bundle exec htmlproofer ./_gh_pages --allow-hash-href --assume-extension --check-external-hash --check-favicon --check-img-http --check-opengraph --disable-external --empty-alt-ignore --internal-domains "expo.getbootstrap.com"

      - name: Upload docs
        uses: actions/upload-artifact@v2
        if: success() && github.repository == 'twbs/bootstrap-expo' && github.ref == 'refs/heads/main'
        with:
          name: docs
          path: ./_gh_pages/

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.repository == 'twbs/bootstrap-expo' && github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download docs
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: ./_gh_pages/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          allow_empty_commit: false
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_gh_pages/
